[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "torch_debugging"
authors = [{name = "zclu", email = "zclu@zju.edu.cn"}]
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "torch",
]
